# Generated by Django 5.2.8 on 2025-12-04 14:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contact_created_at_contact_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[accounts.models.validate_image, accounts.models.validate_image_size]),
        ),
    ]
